nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js

npmPublishRegistry: "http://localhost:4873/"

npmAlwaysAuth: false

npmAuthIdent: "username:password"

unsafeHttpWhitelist:
  - "localhost"
